import { AWBWBuildingsInfo, AWBWPlayerInfo, AWBWPlayersInfo, AWBWTerrainInfo } from "./awbw_types";
import { COPowerType, Coordinate, PlayerInfo, PlayersInfo, Terrain } from "./types";

export function getTerrain(terrainInfo: AWBWTerrainInfo, buildingsInfo: AWBWBuildingsInfo, x: Coordinate, y: Coordinate): Terrain {
    const terrain_id: number | undefined = terrainInfo[x]?.[y]?.terrain_id || buildingsInfo[x]?.[y]?.terrain_id;
    if (!terrain_id) {
        throw new Error(`Couldn't get terrain at x=${x}, y=${y}`)
    }
    return convertTileIdToTerrain(terrain_id);
}

export function parsePlayersInfo(playersInfo: AWBWPlayersInfo): PlayersInfo {
    const ret_val: PlayersInfo = {}
    for (let playerInfo in playersInfo) {
        const player_info: PlayerInfo = parsePlayerInfo(playersInfo[playerInfo])
        ret_val[player_info.id] = player_info
    }
    return ret_val
}

function parsePlayerInfo(playerInfo: AWBWPlayerInfo): PlayerInfo {
    return {
        num: playerInfo.players_order,
        id: playerInfo.players_id,
        co: playerInfo.players_co_id,
        cop: (playerInfo.players_co_power_on == "Y") ? COPowerType.COP : ((playerInfo.players_co_power_on == "S" ? COPowerType.SCOP : COPowerType.None)),
        copMeter: playerInfo.players_co_power,
        funds: playerInfo.players_funds,
        numCities: playerInfo.cities,
        numCommTowers: playerInfo.towers
    }
}

export function convertTileIdToTerrain(id: number): Terrain {
    // scraped from https://awbw.amarriner.com/terrain_map.php
    const tile: Terrain | undefined = {
        1: Terrain.Plains,
        2: Terrain.Mountain,
        3: Terrain.Woods,
        4: Terrain.River,
        5: Terrain.River,
        6: Terrain.River,
        7: Terrain.River,
        8: Terrain.River,
        9: Terrain.River,
        10: Terrain.River,
        11: Terrain.River,
        12: Terrain.River,
        13: Terrain.River,
        14: Terrain.River,
        15: Terrain.Road,
        16: Terrain.Road,
        17: Terrain.Road,
        18: Terrain.Road,
        19: Terrain.Road,
        20: Terrain.Road,
        21: Terrain.Road,
        22: Terrain.Road,
        23: Terrain.Road,
        24: Terrain.Road,
        25: Terrain.Road,
        26: Terrain.Bridge,
        27: Terrain.Bridge,
        28: Terrain.Sea,
        29: Terrain.Shoal,
        30: Terrain.Shoal,
        31: Terrain.Shoal,
        32: Terrain.Shoal,
        33: Terrain.Reef,
        34: Terrain.City,
        35: Terrain.Base,
        36: Terrain.Airport,
        37: Terrain.Port,
        38: Terrain.City,
        39: Terrain.Base,
        40: Terrain.Airport,
        41: Terrain.Port,
        42: Terrain.HQ,
        43: Terrain.City,
        44: Terrain.Base,
        45: Terrain.Airport,
        46: Terrain.Port,
        47: Terrain.HQ,
        48: Terrain.City,
        49: Terrain.Base,
        50: Terrain.Airport,
        51: Terrain.Port,
        52: Terrain.HQ,
        53: Terrain.City,
        54: Terrain.Base,
        55: Terrain.Airport,
        56: Terrain.Port,
        57: Terrain.HQ,
        81: Terrain.City,
        82: Terrain.Base,
        83: Terrain.Airport,
        84: Terrain.Port,
        85: Terrain.HQ,
        86: Terrain.City,
        87: Terrain.Base,
        88: Terrain.Airport,
        89: Terrain.Port,
        90: Terrain.HQ,
        91: Terrain.City,
        92: Terrain.Base,
        93: Terrain.Airport,
        94: Terrain.Port,
        95: Terrain.HQ,
        96: Terrain.City,
        97: Terrain.Base,
        98: Terrain.Airport,
        99: Terrain.Port,
        100: Terrain.HQ,
        101: Terrain.Pipe,
        102: Terrain.Pipe,
        103: Terrain.Pipe,
        104: Terrain.Pipe,
        105: Terrain.Pipe,
        106: Terrain.Pipe,
        107: Terrain.Pipe,
        108: Terrain.Pipe,
        109: Terrain.Pipe,
        110: Terrain.Pipe,
        111: Terrain.LoadedMissileSilo,
        112: Terrain.MissileSilo,
        113: Terrain.Pipeseam,
        114: Terrain.Pipeseam,
        115: Terrain.BrokenPipe,
        116: Terrain.BrokenPipe,
        117: Terrain.Airport,
        118: Terrain.Base,
        119: Terrain.City,
        120: Terrain.HQ,
        121: Terrain.Port,
        122: Terrain.Airport,
        123: Terrain.Base,
        124: Terrain.City,
        125: Terrain.HQ,
        126: Terrain.Port,
        127: Terrain.CommTower,
        128: Terrain.CommTower,
        129: Terrain.CommTower,
        130: Terrain.CommTower,
        131: Terrain.CommTower,
        132: Terrain.CommTower,
        133: Terrain.CommTower,
        134: Terrain.CommTower,
        135: Terrain.CommTower,
        136: Terrain.CommTower,
        137: Terrain.CommTower,
        138: Terrain.Lab,
        139: Terrain.Lab,
        140: Terrain.Lab,
        141: Terrain.Lab,
        142: Terrain.Lab,
        143: Terrain.Lab,
        144: Terrain.Lab,
        145: Terrain.Lab,
        146: Terrain.Lab,
        147: Terrain.Lab,
        148: Terrain.Lab,
        149: Terrain.Airport,
        150: Terrain.Base,
        151: Terrain.City,
        152: Terrain.CommTower,
        153: Terrain.HQ,
        154: Terrain.Lab,
        155: Terrain.Port,
        156: Terrain.Airport,
        157: Terrain.Base,
        158: Terrain.City,
        159: Terrain.CommTower,
        160: Terrain.HQ,
        161: Terrain.Lab,
        162: Terrain.Port,
        163: Terrain.Airport,
        164: Terrain.Base,
        165: Terrain.City,
        166: Terrain.CommTower,
        167: Terrain.HQ,
        168: Terrain.Lab,
        169: Terrain.Port,
        170: Terrain.Airport,
        171: Terrain.Base,
        172: Terrain.City,
        173: Terrain.CommTower,
        174: Terrain.HQ,
        175: Terrain.Lab,
        176: Terrain.Port,
        181: Terrain.Airport,
        182: Terrain.Base,
        183: Terrain.City,
        184: Terrain.CommTower,
        185: Terrain.HQ,
        186: Terrain.Lab,
        187: Terrain.Port,
        188: Terrain.Airport,
        189: Terrain.Base,
        190: Terrain.City,
        191: Terrain.CommTower,
        192: Terrain.HQ,
        193: Terrain.Lab,
        194: Terrain.Port,
        195: Terrain.Teleporter
    }[id]
    if (!tile) {
        throw new Error(`Couldn't recognize tile id=${id}`)
    }
    return tile;
}